### ISSUE TITLE
빨리 봇업데이트를 해주기를 원합니다.

### ISSUE THREAD

**Issue by ment12da** [yunho0508/KKuTu-Bot#1]
아.빨.리.요

(~~제 봇에 붙여넣기 해야한단 말이에욧!~~)

**Comment by yunho0508** [comment]
여기에 올라오지 않은 기능들은 태스트 기능들이니, 조금만 기다려 주시기 바랍니다!

**Comment by ment12da** [comment]
한마디로 ~~**시.공.좋.아**~~ 이 말입니다
